version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: refresher_tapper_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - refresher_tapper_network

  server:
    build: ./server
    container_name: refresher_tapper_server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server  # Монтируем всю папку server
      - /server/node_modules  # Исключаем node_modules из монтирования
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--experimental-vm-modules
      - MONGO_URI=${MONGO_URI}
    networks:
      - refresher_tapper_network

  bot:
    build: ./bot
    container_name: refresher_tapper_bot
    restart: always
    volumes:
      - ./bot:/bot  # Монтируем всю папку bot
    depends_on:
      - server
    environment:
      - TOKEN=${TOKEN}
      - WEB_APP_URL=${WEB_APP_URL}
    networks:
      - refresher_tapper_network

volumes:
  mongo_data:
networks:
  refresher_tapper_network: